default_language_version:
  python: "3.9"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: end-of-file-fixer
      types: [python]
    - id: trailing-whitespace
      types: [python]
    # - id: isort
    #   args: [--settings-file=setup.cfg]
    # - id: black
    #   args: [--line-length=120]
    # - id: flake8
    #   args: [--config=setup.cfg]
    # - id: mypy
    #   exclude: tests/
    #   args: [--config-file, setp.cfg]
    #   additional_dependencies: []
    #   pass_filenames: false
